# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6b06e15e04e3496d48798df1ae1726543ac9c315cb49ec738b0919236d98ef82eb6e6665e37b6977aa870b4f278bdbe4ec07736fa2aa2b224fa5042ff8e87c

test:
  secret_key_base: bf4da70acc0cc5d74c79c880fddfff1c010a45cc6f4f521195e9805b5a2366fedc6610b1d100f1f2e43b0442f52644629700e1a923dfe6a1a13063490b880419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
